# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Alyssa Bulatek
tagline:          'Home'
description:      'Astronomical detective in training. Never slowing down.'
url:              http://abulatek.github.io
baseurl:          /
